pub mod parser;
pub mod engine;
pub mod planner;
pub mod executor;
pub mod vectorized;
pub mod parallel;
pub mod downsample_router;
pub mod optimizer;
pub mod cost_optimizer;
pub mod cache;
pub mod frequency;
pub mod router;

pub use parser::parse_promql;
pub use parser::Expr;
pub use engine::{QueryEngine, QueryResult};
pub use planner::{QueryPlanner, QueryPlan};
pub use executor::{QueryExecutor, ExecutionContext};
pub use vectorized::VectorizedEngine;
pub use parallel::{ParallelQueryExecutor, ParallelConfig, ParallelContext};
pub use downsample_router::{DownsampleRouter, DownsampleRoute, DownsamplePolicy, DownsampleQueryExecutor};
pub use optimizer::{QueryOptimizer, OptimizationStats};
pub use cost_optimizer::{CostBasedOptimizer, OptimizerConfig, StatsManager, CostModel, OptimizationRule};
pub use cache::{ThreadSafeQueryCache, CacheConfig, CacheKey, CacheStats};
pub use frequency::{FrequencyTracker, FrequencyConfig, normalize_query};
pub use router::QueryRouter;